version: "3"

services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"

  backend:
    container_name: server
    build: ./server
    environment:
      - MONGODB_URI=mongodb://mongo:27017/todoApp
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - mongodb

  frontend:
    container_name: client
    build: ./client
    environment:
      - VITE_APP_BACKEND_API=http://localhost:8081
    ports:
      - "5713:5713"
    depends_on:
      - backend
